#!/bin/bash -eux
# DESC: Minimize VirtualBox image.

## Functions
log() {
  echo "$(date +"[%F %X,000]") $(hostname) $1"
}

die() {
  log "[FAIL] $1" >&2 && exit 1
}

# Zero out the free space to save space in the final image. Contiguous zeroed space compresses down to nothing.
log '[INFO] Zeroing out empty area to save space in the final image.'
sudo dd if=/dev/zero of=/EMPTY bs=1M || log "[INFO] dd exit code $? is suppressed"
sudo rm -f /EMPTY

# Block until the empty file has been removed, otherwise, Packer will try to kill the box while the disk is still full (this is bad)
sudo sync

exit $?
